extends "NormalLevel.gd"

func _init():
	tiles = [G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,G.TYPE_DOG,
			G.TYPE_DOG,G.TYPE_DOG]